name: Build

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'


jobs:
  ubuntu:
    name: ${{ matrix.ubuntu_image }}
    runs-on: ${{ matrix.ubuntu_image }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu_image: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: cmake -DCMAKE_PREFIX_PATH=${{ github.workspace }}/install -DCMAKE_INSTALL_PREFIX=install -Bbuild -S.
      - name: Build
        run: cmake --build build

